
class COLUMN_NAMES:
    PATTERN = "PATTERN"
    LOCUS_LENGTH = "LOCUS_LENGTH"
    REFERENCE = "REFERENCE"
    ALLELE_1 = "ALLELE_1"
    ALLELE_2 = "ALLELE_2"
    REPEAT_LENGTH_1 = "REPEAT_LENGTH_1"
    REPEAT_LENGTH_2 = "REPEAT_LENGTH_2"
    REPEAT_LENGTH_3 = "REPEAT_LENGTH_3"
    REPEAT_LENGTH_4 = "REPEAT_LENGTH_4"
    REPEAT_LENGTH_5 = "REPEAT_LENGTH_5"
    REPEAT_LENGTH_6 = "REPEAT_LENGTH_6"
    REPEAT_SUPPORT_1 = "REPEAT_SUPPORT_1"
    REPEAT_SUPPORT_2 = "REPEAT_SUPPORT_2"
    REPEAT_SUPPORT_3 = "REPEAT_SUPPORT_3"
    REPEAT_SUPPORT_4 = "REPEAT_SUPPORT_4"
    REPEAT_SUPPORT_5 = "REPEAT_SUPPORT_5"
    REPEAT_SUPPORT_6 = "REPEAT_SUPPORT_6"

    
    